services:
  peer1:
    build: .
    container_name: peer1
    networks:
      macvlan_network:
        ipv4_address: 10.22.249.201
    environment:
      - NODE_ID=peer1
      - DOCKER_BOOL=1

  peer2:
    build: .
    container_name: peer2
    networks:
      macvlan_network:
        ipv4_address: 10.22.249.202
    environment:
      - NODE_ID=peer2
      - DOCKER_BOOL=1

  peer3:
    build: .
    container_name: peer3
    networks:
      macvlan_network:
        ipv4_address: 10.22.249.203
    environment:
      - NODE_ID=peer3
      - DOCKER_BOOL=1

networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: wlp0s20f3
    ipam:
      config:
        - subnet: 10.22.249.0/24
          gateway: 10.22.249.1