services:
  peer1:
    build: .
    container_name: peer1
    networks:
      - p2p-network
    ports:
      - "4113:4113"
      - "4114:4114"
    environment:
      - NODE_ID=peer1

  peer2:
    build: .
    container_name: peer2
    networks:
      - p2p-network
    ports:
      - "5113:4113"
      - "5114:4114"
    environment:
      - NODE_ID=peer2

  peer3:
    build: .
    container_name: peer3
    networks:
      - p2p-network
    ports:
      - "6113:4113"
      - "6114:4114"
    environment:
      - NODE_ID=peer3

networks:
  p2p-network:
    driver: bridge