services:
  peer1:
    build: .
    container_name: peer1
    networks:
      p2p-network:
        ipv4_address: 192.168.1.102
    environment:
      - NODE_ID=peer1
      - DOCKER_BOOL=1

  peer2:
    build: .
    container_name: peer2
    networks:
      p2p-network:
        ipv4_address: 192.168.1.103
    environment:
      - NODE_ID=peer2
      - DOCKER_BOOL=1

  peer3:
    build: .
    container_name: peer3
    networks:
      p2p-network:
        ipv4_address: 192.168.1.104
    environment:
      - NODE_ID=peer3
      - DOCKER_BOOL=1

networks:
  p2p-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24